### ISSUE TITLE
Safari and canvas size

### ISSUE THREAD

**Issue by sb895** [cambridgeltl/chat#2]
Raised by Reviewer 2:

The website provides a usable and clear interface to the data.  A minor comment, is that in the bar graph view, on my browser (Safari) and canvas size, only every other bar is labeled.  While I can ascertain the identity of the bars by hovering the mouse over it, it would be more convenient if every bar were labeled.

**Comment by spyysalo** [comment]
Replicated and reduced to static version with latest chart.js:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.js"></script>
  </head>
  <body>
    <canvas class="chart" id="chart-1"></canvas>
  </body>
<script>
window.onload = function() {
    var ctx1 = document.getElementById("chart-1").getContext("2d");
    ctx1.canvas.height = 400;
    window.chart1 = new Chart(ctx1, {
        "type": "bar",
        "data": {
            "datasets": [{
                "data": [0.1,-0.4,0.2,0.3,0.3,0.3,0.1,0.3,0.2,0.5],
             }],
            "labels": [
                "A","B","C","D","E","F","G","H",
                "QUITE A LONG LABEL TEXT",
                "ANOTHER QUITE LONG LABEL TEXT"
            ]
        },
        "options":  {
            "maintainAspectRatio": false,
        }
    });
};
</script>
</html>
```

The trigger appears to be the pair of long label texts.

**Comment by spyysalo** [comment]
Simpler yet: https://jsfiddle.net/p3yvdtt8/

**Comment by spyysalo** [comment]
Related: https://github.com/chartjs/Chart.js/issues/358, https://github.com/chartjs/Chart.js/pull/2704, https://github.com/chartjs/Chart.js/issues/3927

**Comment by spyysalo** [comment]
Solution: `autoSkip: false` (ht: https://github.com/chartjs/Chart.js/issues/3346#issuecomment-249057932)
