### ISSUE TITLE
Guidelines for the appropriate use of API calls

### ISSUE THREAD

**Issue by sb895** [cambridgeltl/chat#4]
Raised by Reviewer 2:

The website provides an API that will be useful for access by scripts.  It would be helpful for the authors to describe on the page some guidelines for the appropriate use of the resource (e.g. no more than 1 query every 3 seconds, etc).

**Comment by spyysalo** [comment]
Committed a description with placeholders for the specific values to <http://chat.lionproject.net/api>.
