### ISSUE TITLE
cprob:: Bug when gene does not have any hallmarks

### ISSUE THREAD

**Issue by averissimo** [cambridgeltl/chat#6]
Example for rflnb gene: http://chat.lionproject.net/?q=rflnb&measure=cprob&chart_type=doughnut&hallmarks=top

It also fails for any random string of characters. **It seems that it fails when dividing by the 0 counts of that gene**

**Comment by sb895** [comment]
Thank you very much for reporting this bug.  It has now been fixed. :-)
